version: '3.8'

services:
  db:
    # https://hub.docker.com/_/postgres
    image: postgres:14.6-bullseye@sha256:f565573d74aedc9b218e1d191b04ec75bdd50c33b2d44d91bcd3db5f2fcea647
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432/tcp'
    volumes:
      - db:/var/lib/postgresql

  app:
    image: node:20.1.0-bullseye-slim@sha256:bc5812b018fa74ea7dbe759cb6c0b456ff96a5c2bc8765e132438f6a75cd6946
    restart: always
    depends_on:
      - db
    command: 'sh -c "apt-get update -y && apt-get install -y openssl && yarn && yarn generate && yarn dev"'
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000/tcp'

volumes:
  db:
