version: '3.8'

services:
  db:
    # https://hub.docker.com/_/postgres
    image: postgres:14.6-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432/tcp'
    volumes:
      - db:/var/lib/postgresql

  app:
    image: node:18.10.0-bullseye-slim
    restart: always
    depends_on:
      - db
    command: 'sh -c "apt-get update -y && apt-get install -y openssl && yarn && yarn generate && yarn dev"'
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000/tcp'

volumes:
  db:
