version: '3.8'

services:
  db:
    image: postgres:14.3-bullseye
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432/tcp'
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:
    driver: local
