version: '3.8'

services:
  db:
    # https://hub.docker.com/_/postgres
    image: postgres:14.6-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432/tcp'
    volumes:
      - db:/var/lib/postgresql

  app:
    image: node:19.9.0-bullseye-slim@sha256:f770c8e133e259556fcbd64d852a1e39ffe2da2814ee58bab3ac985fa9b50da5
    restart: always
    depends_on:
      - db
    command: 'sh -c "apt-get update -y && apt-get install -y openssl && yarn && yarn generate && yarn dev"'
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000/tcp'

volumes:
  db:
