version: '3.8'

services:
  db:
    # https://hub.docker.com/_/postgres
    image: postgres:14.3-bullseye
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432/tcp'
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:
    driver: local
