name: Build Docker Image

on:
  push:
    paths-ignore:
      - '**.md'
    branches-ignore:
      - 'renovate/**'

  release:
    types:
      - published

  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/slashnephy/annict2spotify
  TARGET_PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare $IMAGE_TAG (on push to master branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
      - name: Prepare $IMAGE_TAG (on push to other branches)
        if: github.event_name == 'push' && github.ref != 'refs/heads/master'
        run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Prepare $IMAGE_TAG (on release)
        if: github.event_name == 'release'
        run: echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: ${{ env.TARGET_PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
