name: Lint

on:
  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn

      - name: Lint
        run: yarn lint
